server:
    servlet:
        context-path: '/lms'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: "root"
    password:

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/bookstore?useUnicode=true&characterEncoding=utf8
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/bookstore?useUnicode=true&characterEncoding=utf8
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/bookstore?useUnicode=true&characterEncoding=utf8
            properties:
                jmxEnabled: true
                initialSize: 5

